/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BluetoothStrip {
    'connect': () => Promise<void>;
    'runCommand': (commandNumber: number) => Promise<void>;
    'setColor': (red: number, green: number, blue: number) => Promise<void>;
  }
  interface BluetoothStripAttributes extends StencilHTMLAttributes {}

  interface MockBluetoothStrip {
    'connect': () => Promise<void>;
    'runCommand': (_: number) => Promise<void>;
    'setColor': (_red: number, _green: number, _blue: number) => Promise<void>;
  }
  interface MockBluetoothStripAttributes extends StencilHTMLAttributes {}

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'BluetoothStrip': Components.BluetoothStrip;
    'MockBluetoothStrip': Components.MockBluetoothStrip;
    'MyApp': Components.MyApp;
  }

  interface StencilIntrinsicElements {
    'bluetooth-strip': Components.BluetoothStripAttributes;
    'mock-bluetooth-strip': Components.MockBluetoothStripAttributes;
    'my-app': Components.MyAppAttributes;
  }


  interface HTMLBluetoothStripElement extends Components.BluetoothStrip, HTMLStencilElement {}
  var HTMLBluetoothStripElement: {
    prototype: HTMLBluetoothStripElement;
    new (): HTMLBluetoothStripElement;
  };

  interface HTMLMockBluetoothStripElement extends Components.MockBluetoothStrip, HTMLStencilElement {}
  var HTMLMockBluetoothStripElement: {
    prototype: HTMLMockBluetoothStripElement;
    new (): HTMLMockBluetoothStripElement;
  };

  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLElementTagNameMap {
    'bluetooth-strip': HTMLBluetoothStripElement
    'mock-bluetooth-strip': HTMLMockBluetoothStripElement
    'my-app': HTMLMyAppElement
  }

  interface ElementTagNameMap {
    'bluetooth-strip': HTMLBluetoothStripElement;
    'mock-bluetooth-strip': HTMLMockBluetoothStripElement;
    'my-app': HTMLMyAppElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
