/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  BluetoothStrip as BluetoothStrip
} from './components/bluetooth-strip/bluetooth-strip';

declare global {
  interface HTMLBluetoothStripElement extends BluetoothStrip, HTMLElement {
  }
  var HTMLBluetoothStripElement: {
    prototype: HTMLBluetoothStripElement;
    new (): HTMLBluetoothStripElement;
  };
  interface HTMLElementTagNameMap {
    "bluetooth-strip": HTMLBluetoothStripElement;
  }
  interface ElementTagNameMap {
    "bluetooth-strip": HTMLBluetoothStripElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "bluetooth-strip": JSXElements.BluetoothStripAttributes;
    }
  }
  namespace JSXElements {
    export interface BluetoothStripAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MockBluetoothStrip as MockBluetoothStrip
} from './components/bluetooth-strip/mock-bluetooth-strip';

declare global {
  interface HTMLMockBluetoothStripElement extends MockBluetoothStrip, HTMLElement {
  }
  var HTMLMockBluetoothStripElement: {
    prototype: HTMLMockBluetoothStripElement;
    new (): HTMLMockBluetoothStripElement;
  };
  interface HTMLElementTagNameMap {
    "mock-bluetooth-strip": HTMLMockBluetoothStripElement;
  }
  interface ElementTagNameMap {
    "mock-bluetooth-strip": HTMLMockBluetoothStripElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mock-bluetooth-strip": JSXElements.MockBluetoothStripAttributes;
    }
  }
  namespace JSXElements {
    export interface MockBluetoothStripAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}

